---
- hosts: all
  vars:
  tasks:
    - name: Installing missing packages kernel-devel
      ansible.builtin.shell:
        cmd: rm -rf /root/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# Touch File
    - name: create inventory file for hack copy
      ansible.builtin.shell:
        cmd: touch /root/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# add hack entry
    - name: oracle server added to hack job inventory file   
      lineinfile:
        path: /root/dbhost
        line: "{{ vbname }} ansible_user=root ansible_password=redhat "
    - name: Work Around for copy file in GUI - using hack inv file gen auth_keys
      ansible.builtin.shell:
        cmd: ansible-playbook -i /root/dbhost /root/VirtualBox-AAP-OracleDB/keys.yml
      register: shell
    - debug: var=shell.stdout_lines
    - name: Work Around for copy file in GUI - using hack inv file and pre-built hardcoded yml file
      ansible.builtin.shell:
        cmd: ansible-playbook -i /root/dbhost /root/VirtualBox-AAP-OracleDB/cp_ora.yml
      register: shell
    - debug: var=shell.stdout_lines