---
- hosts: all
  vars:

  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /etc/foo.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: Add oracle server to /root/dbhost inventory file for hack copy job
      lineinfile:
      path: /root/dbhost
      line: "{{ vbname }}"