---
- hosts: all
  vars:
  tasks:
    - name: Installing missing packages kernel-devel
      ansible.builtin.shell:
        cmd: rm -rf /root/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# Touch File
    - name: create inventory file for hack copy
      ansible.builtin.shell:
        cmd: touch /root/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# add hack entry
    - name: oracle server added to hack job inventory file   
      lineinfile:
        path: /root/dbhost
        line: "{{ vbname }} ansible_user=root ansible_password=redhat "