---
- hosts: all
  vars:
  tasks:
  - name: Add New VBox server to control.local /etc/hosts file   
    lineinfile:
      path: /etc/hosts
      line: "{{ vbvmip }}     {{ vbvm }}"
  - name: remove inventory file for hack copy
    ansible.builtin.shell:
      cmd: rm -rf /root/software/dbhost
    register: shell
  - debug: var=shell.stdout_lines
# Touch File
  - name: create inventory file for hack copy
    ansible.builtin.shell:
      cmd: mkdir -p /root/software
    register: shell
  - debug: var=shell.stdout_lines
# Touch File
  - name: create inventory file for hack copy
    ansible.builtin.shell:
      cmd: touch /root/software/dbhost
    register: shell
  - debug: var=shell.stdout_lines
# add hack entry
  - name: Create local inventory file /root/dbhost on AAP server   
    lineinfile:
      path: /root/software/dbhost
      line: "{{ vbvm }} ansible_user=root ansible_password=redhat "
  - name: ansible-core  on "{{ inventory_hostname }}"
    ansible.builtin.shell:
      cmd: dnf install ansible-core -y
    register: shell
  - debug: var=shell.stdout_lines
  - name: ansible-galaxy collection install ansible.posix on "{{ inventory_hostname }}"
    ansible.builtin.shell:
      cmd: ansible-galaxy collection install ansible.posix
    register: shell
  - debug: var=shell.stdout_lines
  - name: Add ssh fingerprint to known_hosts file on AAP server for server "{{ vbvm }}"
    ansible.builtin.shell:
      cmd: ssh-keyscan -H "{{ vbvm }}" >> ~/.ssh/known_hosts
    register: shell
  - debug: var=shell.stdout_lines
  - name: Work Around for copy file in GUI - gen auth_keys inventory file /root/dbhost on AAP
    ansible.builtin.shell:
      cmd: ansible-playbook -i /root/software/dbhost /root/AnsibleAutomationPlatform-OracleDB/keys.yml
    register: shell
  - debug: var=shell.stdout_lines

