---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Untar Oracle Binaries
      ansible.builtin.shell:
        cmd: tar -xzvf ora19c.tar.gz
        chdir: /oracle
      register: shell
    - debug: var=shell.stdout_lines
    - name: Set correct hostname in listener.ora
      ansible.builtin.replace:
        path: /oracle/app/product/19c/network/admin/listener.ora
        regexp: change_hostname
        replace: "{{ inventory_hostname }}"
    - name: Set correct hostname in tnsnames.ora
      ansible.builtin.replace:
        path: /oracle/app/product/19c/network/admin/tnsnames.ora
        regexp: change_hostname
        replace: "{{ inventory_hostname }}"
      - name: start listener
      ansible.builtin.shell:
        cmd: lsnrctl start 
      register: shell
    - debug: var=shell.stdout_lines
     - name: Start DB
       shell: |
             sqlplus / as sysdba
             startup;
             EOF
       register: user_output
    - debug: var=user_output.stdout_lines 
