---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
    oracle_sid: ANSDB 
    oracle_base: /oracle/app
    oracle_home: /oracle/app/product/19c
  tasks:
    - name: start listener
      ansible.builtin.shell:
        cmd: export ORACLE_HOME={{ oracle_home }}; export  ORACLE_BASE:={{ oracle_base }}; export ORACLE_SID:={{ oracle_sid }}; $ORACLE_HOME/bin/lsnrctl start
      ignore_errors: true
      register: shell
    - debug: var=shell.stdout_lines
    - name: start database
      ansible.builtin.shell: 
        cmd: | 
          export ORACLE_HOME={{ oracle_home }}; 
          export ORACLE_BASE:={{ oracle_base }}; 
          export ORACLE_SID:={{ oracle_sid }};
          $ORACLE_HOME/bin/sqlplus / as sysdba << eof 
          startup 
          eof 
      register: shell
    - debug: var=shell.stdout_lines
