---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent

  tasks:
    - name: start listener
      ansible.builtin.shell:
        cmd: lsnrctl start 
      register: shell
    - debug: var=shell.stdout_lines
    - name: Start DB
      shell: |
             sqlplus / as sysdba
             startup;
             EOF
      register: user_output
    - debug: var=user_output.stdout_lines 
