---
- hosts: all
  tasks:
    - name: Work Around for copy file in GUI - using hack inv file and pre-built hardcoded yml file
      ansible.builtin.shell:
        cmd: ansible-playbook -i /root/dbhost /root/VirtualBox-AAP-OracleDB/cp_ora.yml
      register: shell
    - debug: var=shell.stdout_lines
