---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Copy AAP (EDA) to EDA server
      ansible.builtin.copy:
        src: /root/software/AAP-bundle-2.4-6.2-x86_64.tar.gz
        dest: /root/software/AAP-bundle-2.4-6.2-x86_64.tar.gz
