---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Copy file to remote host
      ansible.builtin.copy:
        src: /root/software/ora19c.tar.gz
        dest: /oracle/ora19c.tar.gz
        owner: oracle
        group: dba
    - name: Copy bash_profile remote host
      ansible.builtin.copy:
        src: /root/software/ora_bash_profile
        dest: /home/oracle/.bash_profile
        owner: oracle
        group: dba