---
- hosts: all
  tasks:
# Missing packages GIT
    - name: Ensure group "ansible" exists
      ansible.builtin.group:
        name: ansible
        state: present
    - name: Add user 'ansible' with a bash shell, appending the group 'ansible' group
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        groups: ansible
        append: yes
        create_home: yes
        comment: Ansible Admin
        password: "{{ opass | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
# Restart sshd
    - name: Generate ssh keys
      ansible.builtin.user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    - name: "Allow ansible user to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" 
        state: "present"
        regexp: "^%ansible"
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
    - name: mkdir 
      ansible.builtin.shell:
        cmd: mkdir -p /home/ansible/software
      register: shell
    - debug: var=shell.stdout_lines
    - name: Copy AAP Software get
      ansible.builtin.copy:
        src: /root/AnsibleAutomationPlatform-OracleDB/get_aap_software
        dest: /home/ansible/software/get_aap_software
        owner: ansible
        group: ansible
        mode: '777'
#    - name: Change the working directory to somedir/ before executing the command
#      become: yes
#      become_user: ansible
#      ansible.builtin.command: /home/ansible/software/get_aap_software
#      chdir: /home/ansible/software

