---
- hosts: all
  vars_prompt:
    - name: REDHAT_UID 
      prompt: What is your Redhat Subsription username
      private: false 
    - name: REDHAT_PWD 
      prompt: What is your Redhat Subsription password
    - name: opass  
      prompt: Set your ansible OS account password 
  tasks:
# Missing packages GIT
    - name: Ensure group "ansible" exists
      ansible.builtin.group:
        name: ansible
        state: present
    - name: Add user 'ansible' with a bash shell, appending the group 'ansible' group
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        groups: root, ansible
        append: yes
        create_home: yes
        comment: Ansible Admin
        password: "{{ opass | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
# Restart sshd
    - name: Generate ssh keys
      ansible.builtin.user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    - name: "Allow ansible user to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" 
        state: "present"
        regexp: "^%ansible"
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
    - name: mkdir 
      ansible.builtin.shell: |
        mkdir -p /home/ansible/software/aap-bundle-2.4-6.2
        chown -R ansible:ansible /home/ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Copy Oracle Software get
      ansible.builtin.copy:
        src: /root/AnsibleAutomationPlatform-OracleDB/get_ora_software
        dest: /home/ansible/software/get_ora_software
        owner: ansible
        group: ansible
        mode: '777'
    - name: Downloading software 
      ansible.builtin.shell:
        cmd: /home/ansible/software/get_ora_software 
        chdir: /home/ansible/software
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Copy AAP Software get
      ansible.builtin.copy:
        src: /root/AnsibleAutomationPlatform-OracleDB/get_aap_software
        dest: /home/ansible/software/aap-bundle-2.4-6.2
        owner: ansible
        group: ansible
        mode: '777'
    - name: Downloading software 
      ansible.builtin.shell:
        cmd: /home/ansible/software/aap-bundle-2.4-6.2/get_aap_software 
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Clean up
      ansible.builtin.file:
        path: /home/ansible/software/aap-bundle-2.4-6.2/get_aap_software 
        state: absent
    - name: Clean up
      ansible.builtin.file:
        path: /home/ansible/software/get_ora_software 
        state: absent
    - name: untar 
      ansible.builtin.shell:
        cmd: tar -xzvf /home/ansible/software/aap-bundle-2.4-6.2/AAP-bundle-2.4-6.2-x86_64.tar.gz 
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Edit inventory set to Ansible Platform control server    
      ansible.builtin.shell:
        cmd: sed -i "s/change_host_name/"{{ inventory_hostname }}"/g" /home/ansible/software/aap-bundle-2.4-6.2/inventory
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Edit inventory file Subscription username  
      ansible.builtin.shell:
        cmd: sed -i "s/REDHAT_UID/"{{ REDHAT_UID }}"/g" /home/ansible/software/aap-bundle-2.4-6.2/inventory
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Edit inventory file Subscription password 
      ansible.builtin.shell:
        cmd: sed -i "s/REDHAT_PWD/"{{ REDHAT_PWD }}"/g" /home/ansible/software/aap-bundle-2.4-6.2/inventory
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines
    - name: Setup AAP if no output then check /home/ansible/software/aap-bundle-2.4-6.2/setup.log
      ansible.builtin.shell:
        cmd: /home/ansible/software/aap-bundle-2.4-6.2/setup.sh
        chdir: /home/ansible/software/aap-bundle-2.4-6.2
      become: true
      become_user: ansible
      register: shell
    - debug: var=shell.stdout_lines    