---
- hosts: all
  vars:
  tasks:
    - name: Add ssh fingerprint to known_hosts file on AAP server for server "{{ ansible_nodename }}"
      ansible.builtin.shell:
        cmd: ssh-keyscan -H "{{ ansible_nodename }}" >> ~/.ssh/known_hosts
      register: shell
    - debug: var=shell.stdout_lines
