---
- hosts: all
  vars:
  tasks:
# Missing packages GIT
    - name: Add the user 'oracle' with a bash shell, appending the group 'dba' and 'oinstall' to the user's groups
      ansible.builtin.user:
        name: oracle
        shell: /bin/bash
        groups: dba,oinstall,oper,backupdba
        append: yes
        create_home: yes
        comment: Oracle Admin
        password: "{{ opass | password_hash('sha512', 'salt') }}"
      register: out
    - debug: var=out.stdout_lines
# Install preinstall-19c packages
    - name: Installing oracle 19c packages
      ansible.builtin.shell:
        cmd: yum -y install oracle-database-preinstall-19c
      register: shell
    - debug: var=shell.stdout_lines
# Filesystem
    - name: Creates directory
      ansible.builtin.file:
        path: /oracle
        state: directory
        owner: oracle
        group: dba
        mode: 0775
