---
- hosts: all
  vars:
  tasks:
# Missing packages GIT
    - name: Add the user 'oracle' with a bash shell, appending the group 'dba' and 'oinstall' to the user's groups
      ansible.builtin.user:
        name: oracle
        shell: /bin/bash
        groups: dba,oinstall,oper,backupdba
        append: yes
        create_home: yes
        comment: Oracle Admin
        password: "{{ opass | password_hash('sha512', 'salt') }}"
# Install preinstall-19c packages
    - name: Installing oracle 19c packages
      ansible.builtin.shell:
        cmd: yum -y install oracle-database-preinstall-19c
      register: shell
    - debug: var=shell.stdout_lines
# Filesystem
    - name: Creates directory
      ansible.builtin.file:
        path: /oracle
        state: directory
        owner: oracle
        group: dba
        mode: 0775
# Enable Root Login
   - name: Enable Root Login
     lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin yes"
           state: present
           backup: yes
     become: yes
     notify:
       - restart ssh

   handlers:
   - name: restart ssh
     systemctl:
       name: sshd
       state: restarted
