---
- hosts: all
  tasks:
# Missing packages GIT
    - name: Ensure group "dba" exists
      ansible.builtin.group:
        name: dba
        state: present
    - name: Ensure group "oinstall" exists
      ansible.builtin.group:
        name: oinstall
        state: present
    - name: Ensure group "oper" exists
      ansible.builtin.group:
        name: oper
        state: present
    - name: Ensure group "backupdba" exists
      ansible.builtin.group:
        name: backupdba
        state: present
    - name: Add the user 'oracle' with a bash shell, appending the group 'dba' and 'oinstall' to the user's groups
      ansible.builtin.user:
        name: oracle
        shell: /bin/bash
        groups: dba,oinstall,oper,backupdba
        append: yes
        create_home: yes
        comment: Oracle Admin
        password: "{{ opass | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
# Install preinstall-19c packages
    - name: Installing oracle 19c packages
      ansible.builtin.shell:
        cmd: yum -y install oracle-database-preinstall-19c
      register: shell
    - debug: var=shell.stdout_lines
# Filesystem
    - name: Creates directory
      ansible.builtin.file:
        path: /oracle
        state: directory
        owner: oracle
        group: dba
    - name: Enable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
    - name: Generate ssh keys
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

