---
- hosts: all
  vars:
  tasks:
    - name: remove inventory file for hack copy
      ansible.builtin.shell:
        cmd: rm -rf /root/software/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# Touch File
    - name: create inventory file for hack copy
      ansible.builtin.shell:
        cmd: touch /root/software/dbhost
      register: shell
    - debug: var=shell.stdout_lines
# add hack entry
    - name: Create local inventory file /root/software/dbhost on "{{ inventory_hostname }}"   
      lineinfile:
        path: /root/software/dbhost
        line: "{{ vbvm }} ansible_user=root ansible_password=redhat "
    - name: Add target server to /etc/hosts file   
      lineinfile:
        path: /etc/hosts
        line: "{{ vbvmip }}     {{ vbvm }}"
    - name: ansible-core  on "{{ inventory_hostname }}"
      ansible.builtin.shell:
        cmd: dnf install ansible-core -y
      register: shell
    - debug: var=shell.stdout_lines
    - name: ansible-galaxy collection install ansible.posix on "{{ inventory_hostname }}"
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install ansible.posix
      register: shell
    - debug: var=shell.stdout_lines
    - name: Add ssh fingerprint to known_hosts file on AAP server for server "{{ vbvm }}"
      ansible.builtin.shell:
        cmd: ssh-keyscan -H "{{ vbvm }}" >> ~/.ssh/known_hosts
      register: shell
    - debug: var=shell.stdout_lines
    - name: Copy files to remote host
      ansible.builtin.synchronize:
        src: /root/software/keys.yml
        dest: /root/software/keys.yml
      delegate_to: "{{ aap_serv }}"
    - name: Work Around for copy file in GUI - gen auth_keys inventory file /root/dbhost on AAP
      ansible.builtin.shell:
        cmd: ansible-playbook -i /root/software/dbhost /root/software/keys.yml
      register: shell
    - debug: var=shell.stdout_lines
