---
- hosts: all
  vars:
  tasks:
    - name: Install EDA - Should take 30 minutes or less check https://"{{ inventory_hostname }}"
      ansible.builtin.shell:
        cmd: sh setup.sh
        chdir: /root/software/aap-bundle-2.4-6.2
