---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: backup EDA Inventoy file  
      ansible.builtin.shell:
        cmd: cp inventory orig-inventory
        chdir: /root/software/aap-bundle-2.4-6.2
      register: shell
    - debug: var=shell.stdout_lines
# Section to edit Inventory file for setup 
    - name: Update Inventoy file with "{{ aap_serv }}" server 
      ansible.builtin.shell:
        cmd: sed -i "s/change_host_name/"{{ aap_serv }}"/g" /root/software/aap-bundle-2.4-6.2/inventory
        chdir: /root/software/aap-bundle-2.4-6.2
    - name: Update Inventoy file with "{{ aap_serv }}" server 
      ansible.builtin.shell:
        cmd: sed -i "s/REDHAT_UID//g" /root/software/aap-bundle-2.4-6.2/inventory
        chdir: /root/software/aap-bundle-2.4-6.2
    - name: Update Inventoy file with "{{ aap_serv }}" server 
      ansible.builtin.shell:
        cmd: sed -i "s/REDHAT_PWD//g" /root/software/aap-bundle-2.4-6.2/inventory
        chdir: /root/software/aap-bundle-2.4-6.2
    - name: Update Inventoy file with "{{ inventory_hostname }}" server 
      ansible.builtin.shell:
        cmd: sed -i "s/EDA_SERVER/"{{ inventory_hostname }}"/g" /root/software/aap-bundle-2.4-6.2/inventory
        chdir: /root/software/aap-bundle-2.4-6.2
# Entry for self ssh 
    - name: passwordless to self  "{{ inventory_hostname }}"
      ansible.builtin.shell:
        cmd: cat id_rsa.pub >> authorized_keys
        chdir: /root/.ssh
# Install EDA
    - name: Run setup.sh to install EDA  
      ansible.builtin.command:
        cmd: /root/software/aap-bundle-2.4-6.2/setup.sh
      register: shell
    - debug: var=shell.stdout_lines