---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: backup EDA Inventoy file  
      ansible.builtin.shell:
        cmd: cp inventory orig-inventory
        chdir: /root/software/aap-bundle-2.4-6.2
      register: shell
    - debug: var=shell.stdout_lines
# Install EDA
    - name: " Run /root/software/aap-bundle-2.4-6.2/setup.sh from {{ inventory_hostname }} as it will not install GUI [ansible.automation_platform_installer.podman : reset podman for awx user to apply configs]  "
      ansible.builtin.command:
        cmd: pwd 