---
- hosts: all
#- hosts: "{{ eda_srv }}"
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
# Missing Ansible modeules 
    - name: Install Missing Ansible module ansible.posix
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install ansible.posix
      register: shell
    - debug: var=shell.stdout_lines
    - name: Add ssh fingerprint to known_hosts file on AAP server for server "{{ ansible_nodename }}"
      ansible.builtin.shell:
        cmd: ssh-keyscan -H "{{ ansible_nodename }}" >> ~/.ssh/known_hosts
      register: shell
    - debug: var=shell.stdout_lines  
    - name: Generate ssh keys
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
    - name: Copy AAP authorized_keys to remote host
      ansible.builtin.synchronize:
        src: ~/.ssh/authorized_keys
        dest: ~/.ssh/aap-authorized_keys
      delegate_to: "{{ ansible_nodename }}"