---
- hosts: all
  vars: 
    thost: "oel94.local"

  gather_facts: true

  tasks:

  - name: Show Gathered Facts ans
    debug:
      msg: "{{ ansible_hostname }}"

  - name: Show Gathered Facts inv
    debug:
      msg: "{{ inventory_hostname }}"
  
  - name: Show Gathered Facts targ
    debug:
      msg: "{{ thost }} next ASU = {{ acu }} next {{ ac }}"
