---
- hosts: all
  become: false

  gather_facts: true

  tasks:

  - name: Show Gathered Facts ans
    debug:
      msg: "{{ ansible_hostname }}"

  - name: Show Gathered Facts inv
    debug:
      msg: "{{ inventory_hostname }}"
  
  - name: Show Gathered Facts vars
    debug:
      msg: "{{ hostvars }}"
