---
- hosts: all
  vars:
  tasks:
    - name: Copy AAP-bundle to "{{ inventory_hostname }}" from "{{ aap_serv }}"
      ansible.builtin.synchronize:
        src: /root/software/keys.yml
        dest: /root/software/keys.yml
      delegate_to: "{{ aap_serv }}"
