---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Add ssh fingerprint to known_hosts file on AAP server for server "{{ ansible_nodename }}"
      ansible.builtin.shell:
        cmd: ssh-keyscan -H "{{ ansible_nodename }}" >> ~/.ssh/known_hosts
      register: shell
    - debug: var=shell.stdout_lines  
    - name: Generate ssh keys
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      delegate_to: "{{ aap_serv }}"