---
- hosts: all
  vars:
  tasks:
    - name: Check that the file exists
      stat:
        path: /root/software/keys.yml
      register: stat_result
    - name: Copy files if they do not exist 
      ansible.builtin.synchronize:
        src: /root/software/keys.yml
        dest: /root/software/keys.yml
      when: stat_result.stat.exists == False 
      delegate_to: "{{ aap_serv }}"
