---
- hosts: localhost
  become: false

  gather_facts: false

  tasks:

  - name: Show Gathered Facts
    debug:
      msg: "{{ hostvars['localhost'].ansible_facts }}"

  - name: Gather date and time only
    setup:
      gather_subset:
        - "date_time"
        - "!min"
    when: ansible_date_time is not defined

  - name: Show Gathered Facts
    debug:
      msg: "{{ ansible_facts }}"

