---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent

  tasks:
    - name: Untar Oracle Binaries
      ansible.builtin.shell:
        cmd: echo $ORACLE_SID
      register: shell
    - debug: var=shell.stdout_lines