---
- hosts: all

  tasks:

  - name: Cat example 1
    shell:
      cmd: cat /Users/ansible/runningvms.lst
    register: VAR
    debug:
    msg: "{{ VAR }}"
  - name: Echo example 2
    shell:
      cmd: "echo {{ VAR.stdout_lines }}"
    register: result

  - name: Show registered variable
    debug:
      var: result

  - name: Show result content only
    debug:
      msg: "{{ result }}"
