---
- hosts: all
  name: Display content of resolv.conf
  tasks:
    - name: Display resolv.conf contents
    - ansible.builtin.debug:
      var: lookup('ansible.builtin.file', '/etc/resolv.conf')

      register: command_output

    - name: Print to console
      debug:
        msg:"{{command_output.stdout}}"
