---
- hosts: all
  tasks:
    - name: Display resolv.conf contents
      ansible.builtin.debug:
        var: lookup('ansible.builtin.file', '/etc/resolv.conf')
      register: command_output

    - name: Print to console
    - debug:
        msg: "{{ out.stdout }}"

