---
  - name: Magic Vars
    hosts: all
    gather_facts: no
    

    tasks:

    - name: What's My Hostname
      debug:
        var: inventory_hostname
    
    - name:  test var
      ansible.builtin.shell:
        cmd: VBoxManage showvminfo "{{ inventory_hostname }}" --machinereadable |grep macaddress1 
      register: shell
    - debug: var=shell.stdout_lines
