---
  - name: Magic Vars
    hosts: all
    gather_facts: no
    

    tasks:

    - name: What's My Hostname
      debug:
        var: inventory_hostname
    
    - name:  test var
      ansible.builtin.shell:
        cmd: cat /etc/hosts | grep "{{ inventory_hostname }}"
      register: shell
    - debug: var=shell.stdout_lines
