---
- hosts: all
  tasks:
# Missing packages GIT
    - name: Installing missing packages git
      ansible.builtin.shell:
        cmd: dnf install git -y
      register: shell
    - debug: var=shell.stdout_lines
# devel
    - name: Installing missing packages kernel-devel
      ansible.builtin.shell:
        cmd: dnf install kernel-devel -y
      register: shell
    - debug: var=shell.stdout_lines
# bzip2
    - name: Installing missing packages bzip2
      ansible.builtin.shell:
        cmd: dnf install bzip2 -y
      register: shell
    - debug: var=shell.stdout_lines
# gcc
    - name: Installing missing packages gcc
      ansible.builtin.shell:
        cmd: dnf install gcc -y
      register: shell
    - debug: var=shell.stdout_lines
# mkdir
    - name: make filesystem for mounting cdrom
      ansible.builtin.shell:
        cmd: mkdir -p /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
# mkdir
    - name: make filesystem for Software
      ansible.builtin.shell:
        cmd: mkdir -p /root/software
      register: shell
    - debug: var=shell.stdout_lines
# mount
    - name: mount cdrom
      ansible.builtin.shell:
        cmd: mount /dev/cdrom /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
# VBoxLinuxAdditions
    - name: This  will install VBoxLinuxAdditions on RHEL 
      ansible.builtin.shell:
        cmd: sh VBoxLinuxAdditions.run
        chdir: /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
    - name: Generate ssh keys
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
# VBoxLinuxAdditions
    - name: change dir, no idea why this is still here 
      ansible.builtin.shell:
        cmd: pwd
        chdir: /root
      register: shell
    - debug: var=shell.stdout_lines
# umount
    - name: unmount cdrom
      ansible.builtin.shell:
        cmd: umount /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
    - name: Enable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
