---
  - name: Magic Vars
    hosts: all
    tasks:
    
    - name:  Running VM's
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage list vms | awk '{ print $1}' | tr -d '"' > /Users/ansible/runningvms.lst 
      register: vmlist
    - debug: var=vmlist.stdout_lines
    - name:  build variable list 
      ansible.builtin.shell:
        cmd: cat /Users/ansible/runningvms.lst 
      register: my_items
    - debug: var=my_items.stdout_lines
    - name: list Vms that are running
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage showvminfo "{{ item }}" --machinereadable |grep macaddress1
        with_items: my_items.stdout_lines

