---
- hosts: all
  tasks:
    - name:  Mount Insert Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage storageattach control.local --storagectl "IDE" --port 1 --device 0 --type dvddrive --medium emptydrive
      register: shell
    - debug: var=shell.stdout_lines
