---
- hosts: all
  tasks:
    - name:  Shutdown control.local to remove dvd (should be better way) ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage controlvm "{{ hostname }}" shutdown
      register: shell
    - debug: var=shell.stdout_lines
# Remove dvd
    - name:  Un Mount Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage storageattach "{{ hostname }}" --storagectl "IDE" --port 1 --device 0 --type dvddrive --medium emptydrive
      register: shell
    - debug: var=shell.stdout_lines
# Startup Control
    - name:  Shutdown control.local to remove dvd (should be better way) ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage startvm "{{ hostname }}" --type headless 
      register: shell
    - debug: var=shell.stdout_lines
