---
- hosts: all
  tasks:
    - name:  Mount Insert Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: VBoxManage storageattach control.local --storagectl "IDE Controller" --port 0 --device 1 --type dvddrive --medium emptydrive
      register: shell
    - debug: var=shell.stdout_lines
