---
- hosts: all
  vars:
  tasks:
    - name:  Mount Insert Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage storageattach "{{ vbvm }}" --storagectl "IDE" --port 1 --device 0 --type dvddrive --medium /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
      register: out
    - debug: var=out.stdout_lines
