---
- hosts: all
  vars:
  tasks:
    - name:  Shutdown "{{ vbvm }}" to remove dvd (should be better way) ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage controlvm "{{ vbvm }}" poweroff 
      register: shell
    - debug: var=shell.stdout_lines
# Adding pause so vm can stop to remove locks
    - name: Pause for 15 seconds before starting again
      pause:
        seconds: 15
# Remove dvd
    - name:  Un Mount Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage storageattach "{{ vbvm }}" --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium emptydrive
      register: shell
    - debug: var=shell.stdout_lines
# Startup Control
    - name:  Startup "{{ vbvm }}" to remove dvd should take 10 Seconds ..
      ansible.builtin.shell:
        cmd: /usr/local/bin/VBoxManage startvm "{{ vbvm }}" --type headless 
      register: shell
    - debug: var=shell.stdout_lines
