---
- hosts: all
  tasks:
    - name: Installing missing packages kernel-devel
      ansible.builtin.shell:
        cmd: dnf install kernel-devel -y
      register: shell
    - debug: var=shell.stdout_lines
    




-- name: Installing missing packages for VirtualBox
#echo " Installing missing packages for VirtualBox"
#dnf install kernel-devel -y
#dnf install bzip2 -y 
#dnf install gcc -y
#mkdir -p /media/cdrom
#mount /dev/cdrom /media/cdrom
#cd /media/cdrom
#sh VBoxLinuxAdditions.run
