---
- hosts: all
  tasks:
    - name: Installing missing packages kernel-devel
      ansible.builtin.shell:
        cmd: dnf install kernel-devel -y
      register: shell
    - debug: var=shell.stdout_lines
# bzip2
    - name: Installing missing packages bzip2
      ansible.builtin.shell:
        cmd: dnf install bzip2 -y
      register: shell
    - debug: var=shell.stdout_lines
# gcc
    - name: Installing missing packages gcc
      ansible.builtin.shell:
        cmd: dnf install gcc -y
      register: shell
    - debug: var=shell.stdout_lines
# mkdir
    - name: make filesystem for mounting cdrom
      ansible.builtin.shell:
        cmd: mkdir -p /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
# mount
    - name: mount cdrom
      ansible.builtin.shell:
        cmd: mount /dev/cdrom /media/cdrom
      register: shell
    - debug: var=shell.stdout_lines
# VBoxLinuxAdditions
    - name: mount cdrom
      ansible.builtin.shell:
        cmd: cd /media/cdrom ; sh VBoxLinuxAdditions.run
      register: shell
    - debug: var=shell.stdout_lines

