---
- hosts: all
  tasks:
    - name:  Mount Insert Guest Additions CD Images ..
      ansible.builtin.shell:
        cmd: VBoxManage storageattach <VM name> --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium emptydrive
      register: shell
    - debug: var=shell.stdout_lines
