---
  - name: Magic Vars
    hosts: all
    vars:
    tasks:    
    - name:  Create file for host are we adding VirtualGuest Image
      ansible.builtin.shell:
        cmd: touch addGI 
        chdir: /Users/ansible 
    - name:  Add host to file
      lineinfile:
        path:  /Users/ansible/addGI 
        line: "{{ vbvm }}"
#    - name: list
#      ansible.builtin.shell:
#        cmd: /usr/local/bin/VBoxManage showvminfo "{{ vbvm }}" --machinereadable |grep macaddress1
#      register: vbsh
#    - debug: var=vbsh.stdout_lines




